spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# show SQL commands in console
spring.jpa.show-sql=true

# formats SQL in console to make it more readable
spring.jpa.properties.hibernate.format_sql=true

# highlights the logs with colors
spring.jpa.properties.hibernate.highlight_sql=true

spring.jpa.hibernate.ddl-auto=validate

# port in which the API will connect
server.port=8080